services:
  - type: web
    name: business-card-render-service
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3200
      - key: HOST
        value: 0.0.0.0
